// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/dhritimannath/notification-service/internal/controllers"
	"github.com/dhritimannath/notification-service/internal/repositories"
	"github.com/dhritimannath/notification-service/internal/services"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := InitDb()
	userRepositoryImpl := repositories.UserRepositoryInit(gormDB)
	userServiceImpl := services.UserServiceInit(userRepositoryImpl)
	userControllerImpl := controllers.UserControllerInit(userServiceImpl)
	subscriptionRepositoryImpl := repositories.SubscriptionRepositoryInit(gormDB)
	subscriptionServiceImpl := services.SubscriptionServiceInit(subscriptionRepositoryImpl)
	subscriptionControllerImpl := controllers.SubscriptionControllerInit(subscriptionServiceImpl)
	initialization := NewInitialization(userRepositoryImpl, userServiceImpl, userControllerImpl, subscriptionRepositoryImpl, subscriptionServiceImpl, subscriptionControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(InitDb)

var userServiceSet = wire.NewSet(services.UserServiceInit, wire.Bind(new(services.UserService), new(*services.UserServiceImpl)))

var userRepoSet = wire.NewSet(repositories.UserRepositoryInit, wire.Bind(new(repositories.UserRepository), new(*repositories.UserRepositoryImpl)))

var userCtrlSet = wire.NewSet(controllers.UserControllerInit, wire.Bind(new(controllers.UserController), new(*controllers.UserControllerImpl)))

var subscriptionServiceSet = wire.NewSet(services.SubscriptionServiceInit, wire.Bind(new(services.SubscriptionService), new(*services.SubscriptionServiceImpl)))

var subscriptionRepoSet = wire.NewSet(repositories.SubscriptionRepositoryInit, wire.Bind(new(repositories.SubscriptionRepository), new(*repositories.SubscriptionRepositoryImpl)))

var subscriptionCtrlSet = wire.NewSet(controllers.SubscriptionControllerInit, wire.Bind(new(controllers.SubscriptionController), new(*controllers.SubscriptionControllerImpl)))
